---
- name: Import Configuration to AAP 2.6
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    controller_hostname: "https://example.com"
    controller_username: "admin"
    controller_password: "TargetPassword123"
    controller_validate_certs: false
    input_path: "/tmp/aap_export"

  tasks:
    - name: Import configuration assets
      ansible.builtin.include_role:
        name: infra.controller_configuration.dispatch
      vars:
        controller_config_dir: "{{ input_path }}"
