---
- name: Import Configuration to AAP 2.6
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    controller_hostname: "aap.zpqkh.sandbox2989.opentlc.com"
    controller_username: "lab-user"
    controller_password: "MjA1MTYzMDA1"
    controller_validate_certs: false
    input_path: "/tmp/aap_export"
    controller_oauthtoken: "nsf6kcM4A6ojmXkL3hA7R4A3t5DAQL"    

  tasks:
    - name: Import configuration assets
      include_role:
        name: dispatch
      vars:
        controller_config_dir: "{{ input_path }}"
