---
- name: Export AAP Controller Configuration
  hosts: all
  gather_facts: false
  vars:
    controller_host: "{{ controller_host }}"
    username: "lab-user"
    password: "MjA1MTYzMDA1"
    controller_hostname: "{{ controller_host }}"
    controller_username: "{{ controller_user }}"
    controller_password: "{{ controller_pw }}"
    controller_validate_certs: false
    output_path: "/tmp/aap_export/"
    valid_tags:
      - all
      - settings
      - credentials
      - credential_types
      - execution_environments
      - groups
      - hosts
      - inventory
      - inventory_sources
      - job_templates
      - notification_templates
      - organizations
      - projects
      - roles
      - teams
      - users
      - workflow_job_templates
      - workflow_job_template_nodes
      - instance_groups
      - applications
      - labels
      - schedules
   
  tasks:
    - name: Generate OAuth2 Token
      ansible.builtin.uri:
        url: "https://{{ controller_host }}/api/controller/v2/tokens/"
        method: POST
        user: "{{ controller_user }}
        password: "{{ controller_pw }}"
        force_basic_auth: true
        status_code: 201
        validate_certs: false  # Change to true if using valid SSL certs
      register: token_response
      #no_log: true  # Prevents credentials and tokens from leaking in logs

    - name: Extract Token into a Fact
      ansible.builtin.set_fact:
        controller_oauthtoken: "{{ token_response.json.token }}"

    - name: Create output directory
      file:
        path: "{{ output_path }}"
        state: directory

    - name: Export all controller objects
      include_role:
        name: filetree_create
      vars:
        file_dump_output_path: "{{ output_path }}"
        clean_assets: true   
