---
- name: Export AAP 2.4/2.6 Configuration
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    controller_hostname: "aap.j445w.sandbox2989.opentlc.com"
    controller_username: "lab-user"
    controller_password: "MTE3MTY3NDIz"
    controller_validate_certs: false
    output_path: "/tmp/aap_export"
    controller_oauthtoken: "nsf6kcM4A6ojmXkL3hA7R4A3t5DAQL"
    valid_tags:
      - all
      - settings
      - credentials
      - credential_types
      - execution_environments
      - groups
      - hosts
      - inventory
      - inventory_sources
      - job_templates
      - notification_templates
      - organizations
      - projects
      - roles
      - teams
      - users
      - workflow_job_templates
      - workflow_job_template_nodes
      - instance_groups
      - applications
      - labels
      - schedules

  tasks:
    - name: Create output directory
      file:
        path: "{{ output_path }}"
        state: directory

    - name: Export all controller objects
      include_role:
        name: filetree_create
      vars:
        file_dump_output_path: "{{ output_path }}"
        clean_assets: true
