---
- name: Import Configuration to AAP 2.6
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    controller_hostname: "aap.zpqkh.sandbox5380.opentlc.com"
    controller_username: "lab-user"
    controller_password: "MjA1MTYzMDA1"
    controller_validate_certs: false
    input_path: "{{ playbook_dir }}/controller_configs"
    controller_oauthtoken: "sVLGxyZrv9kgjweZfXkmITqIqUA42P"
    valid_roles:
      - settings
      - execution_environments
      - groups
      - hosts
      - inventory
      - inventory_sources
      - job_templates
      - notification_templates
      - organizations
      - projects
      - roles
      - teams
      - users
      - workflow_job_templates
      - workflow_job_template_nodes
      - instance_groups
      - applications
      - labels
      - schedules

  tasks:
    - name: Import configuration assets
      include_role:
        name: dispatch
      vars:
        controller_config_dir: "{{ input_path }}"
