---
- name: Configure Ansible Controller
  hosts: all
  #connection: local
  gather_facts: false
  collections:
    - ansible.controller
    - infra.aap_configuration

  vars:
    # Target server connection details
    controller_username: "{{ controller_user }}"
    controller_password: "{{ controller_pw }}" 
    controller_validate_certs: false

  tasks:
    - name: Create a new Job Template
      ansible.controller.job_template:
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_user }}"
        controller_password: "{{ controller_pw }}"
        validate_certs: false      
        name: "job Importado"
        description: "job Importado"
        job_type: "run"
        inventory: "Bastion"
        project: "ACV2TEST"
        playbook: "AAP_export_Configuration.yml"
        credentials:
          - "Bastion"
        execution_environment: "Control Plane Execution Environment"
        state: present


    - name: Create a new Job Template
      ansible.controller.job_template:
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_user }}"
        controller_password: "{{ controller_pw }}"
        validate_certs: false      
        name: "AAP_Exportar2"
        description: ""
        organization: "Default"
        project: "ACV2TEST"
        inventory: "Bastion"
        playbook: "AAP_export_controller_objects.yml"
        scm_branch: ""
        forks: 0
        limit: ""
        verbosity: 0
        job_type: "run"
        job_slice_count: 1
        use_fact_cache: false
        credentials:
          - "Bastion"
        allow_simultaneous: false
        ask_scm_branch_on_launch: false
        ask_diff_mode_on_launch: false
        ask_tags_on_launch: false
        ask_skip_tags_on_launch: false
        ask_job_type_on_launch: false
        ask_verbosity_on_launch: false
        ask_variables_on_launch: false
        ask_inventory_on_launch: false
        ask_limit_on_launch: false
        ask_credential_on_launch: false
        ask_execution_environment_on_launch: false
        ask_labels_on_launch: false
        ask_forks_on_launch: false
        ask_job_slice_count_on_launch: false
        ask_timeout_on_launch: false
        ask_instance_groups_on_launch: false
        extra_vars:
          controller_user: lab-user
          controller_pw: NDE3NjA1OTcy
          controller_hostname: aap.bnzvd.sandbox5552.opentlc.com
          output_path: /tmp/aap_export
          input_path: /tmp/aap_export
          dir_orgs_vars: ./tmp/controller_backup
          valid_tags:
            - all
            - settings
            - credentials
            - credential_types
            - execution_environments
            - groups
            - hosts
            - inventory
            - inventory_sources
            - job_templates
            - notification_templates
            - organizations
            - projects
            - roles
            - teams
            - users
            - workflow_job_templates
            - workflow_job_template_nodes
            - instance_groups
            - applications
            - labels
            - schedules
          valid_roles:
            - settings
            - credentials
            - credential_types
            - execution_environments
            - groups
            - hosts
            - inventories
            - inventory_sources
            - job_templates
            - notification_templates
            - organizations
            - projects
            - roles
            - teams
            - users
            - workflow_job_templates
            - instance_groups
            - applications
            - labels
            - schedules
        job_tags: ""
        force_handlers: false
        skip_tags: ""
        start_at_task: ""
        timeout: 0
        execution_environment: "Control Plane Execution Environment"
        host_config_key: ""
        survey_enabled: false
        become_enabled: false
        diff_mode: false
        webhook_service: ""
        prevent_instance_group_fallback: false        
