---
- name: Authenticate with AAP Controller and Get Token
  hosts: localhost
  gather_facts: false
  vars:
    controller_host: "localhost"
    username: "lab-user"
    password: "MjA1MTYzMDA1"

  tasks:
    - name: Generate OAuth2 Token
      ansible.builtin.uri:
        url: "https://aap.zpqkh.sandbox5380.opentlc.com/api/controller/v2/tokens/"
        method: POST
        user: "lab-user"
        password: "MjA1MTYzMDA1"
        force_basic_auth: true
        status_code: 201
        validate_certs: false  # Change to true if using valid SSL certs
      register: token_response
      #no_log: true  # Prevents credentials and tokens from leaking in logs

    - name: Extract Token into a Fact
      ansible.builtin.set_fact:
        aap_token: "{{ token_response.json.token }}"
