---
- name: Export AAP Controller Configuration
  hosts: all
  gather_facts: false
   
  tasks:
    - name: Generate OAuth2 Token
      ansible.builtin.uri:
        url: "https://{{ controller_host }}/api/controller/v2/tokens/"
        method: POST
        user: "{{ controller_user }}
        password: "{{ controller_pw }}"
        force_basic_auth: true
        status_code: 201
        validate_certs: false  # Change to true if using valid SSL certs
      register: token_response
      #no_log: true  # Prevents credentials and tokens from leaking in logs

    - name: Extract Token into a Fact
      ansible.builtin.set_fact:
        controller_oauthtoken: "{{ token_response.json.token }}"
