---
- name: Importar inventarios al AAP Controller
  hosts: all
  gather_facts: false
  vars:
    controller_configuration_inventories_enforce_defaults: false
  vars_files:
    controller_inventories.yml

  tasks:
    - name: Importar inventarios
      ansible.controller.inventory:
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_user }}"
        controller_password: "{{ controller_pw }}"
        validate_certs: false
        name: "{{ __controller_inventory_item.name | mandatory }}"
        new_name: "{{ __controller_inventory_item.new_name | default(omit, true) }}"
        copy_from: "{{ __controller_inventory_item.copy_from | default(omit, true) }}"
        description: "{{ __controller_inventory_item.description | default(('' if controller_configuration_inventories_enforce_defaults else omit), true) }}"
        organization: "{{ __controller_inventory_item.organization.name | default(__controller_inventory_item.organization) | mandatory }}"
        instance_groups: "{{ __controller_inventory_item.instance_groups | default(([] if controller_configuration_inventories_enforce_defaults else omit), true) }}"
        input_inventories: "{{ __controller_inventory_item.input_inventories | default(([] if controller_configuration_inventories_enforce_defaults else omit), true) }}"
        variables: "{{ __controller_inventory_item.variables | regex_replace('{  {', '{_~~remove~~_{') | regex_replace('_~~remove~~_', '') if (__controller_inventory_item.variables is defined and __controller_inventory_item.variables) else ({} if controller_configuration_inventories_enforce_defaults else omit) }}"
        kind: "{{ __controller_inventory_item.kind | default(('' if controller_configuration_inventories_enforce_defaults else omit), true) }}"
        host_filter: "{{ __controller_inventory_item.host_filter | default(('' if controller_configuration_inventories_enforce_defaults else omit), true) }}"
        prevent_instance_group_fallback: "{{ __controller_inventory_item.prevent_instance_group_fallback | default((false if controller_configuration_inventories_enforce_defaults else omit), true) }}"
        state: "{{ __controller_inventory_item.state | default(platform_state | default('present')) }}"

      loop: "{{ controller_inventories }}"
      loop_control:
        loop_var: __controller_inventory_item
        label: "Importando: {{ __controller_inventory_item.name }}"        
