---
- name: Importar execution environments al AAP Controller
  hosts: all
  gather_facts: false
  vars:
    controller_configuration_execution_environments_enforce_defaults: false
  vars_files:
    current_execution_environments.yaml

  tasks:
    - name: Importar execution environments
      ansible.controller.execution_environment:
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_user }}"
        controller_password: "{{ controller_pw }}"
        validate_certs: false  

        name: "{{ __execution_environments_item.name | mandatory }}"
        new_name: "{{ __execution_environments_item.new_name | default(omit, true) }}"
        description: "{{ __execution_environments_item.description | default(('' if controller_configuration_execution_environments_enforce_defaults else omit), true) }}"
        image: "{{ __execution_environments_item.image | mandatory }}"
        organization: "{{ __execution_environments_item.organization.name | default(__execution_environments_item.organization | default(('' if controller_configuration_execution_environments_enforce_defaults else omit), true)) }}"
        credential: "{{ __execution_environments_item.credential | default(('' if controller_configuration_execution_environments_enforce_defaults else omit), true) }}"
        pull: "{{ __execution_environments_item.pull | default(('missing' if controller_configuration_execution_environments_enforce_defaults else omit), true) }}"
        state: "{{ __execution_environments_item.state | default(platform_state | default('present')) }}"

      loop: "{{ controller_execution_environments }}"
      loop_control:
        loop_var: __execution_environments_item
        label: "Importando: {{ __execution_environments_item.name }}"



      #Importando:
