---
- name: Info de VM
  hosts: all
  collections:
    - vmware.vmware
    - community.vmware  
 
  tasks:
    - name: Optener info de la VM
      vmware.vmware.guest_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        guest_name: "my_vm"
      delegate_to: localhost
      register: vm_info
