---
- name: "Run the following infra.controller_configuration roles: {{ valid_roles | join(', ') }}"
  ansible.builtin.include_role:
    name: "{{ role }}"
    apply:
      tags: "{{ role }}"
  #when: vars[valid_roles] is defined
  tags: always
  loop: "{{ valid_roles }}"
  loop_control:
    loop_var: role
  vars:
    assign_galaxy_credentials_to_org: "false"
    assign_default_ee_to_org: "false"
    assign_notification_templates_to_org: "false"

- name: Display errors and fail
  when:
    - controller_configuration_role_errors is defined
    - controller_configuration_role_errors is mapping
    - controller_configuration_role_errors | dict2items | selectattr('value', 'ne', []) | list | length > 0
  ansible.builtin.debug:
    msg:
      - "Errors encountered applying configurations:"
      - "{{ controller_configuration_role_errors }}"
  failed_when: controller_configuration_role_errors | dict2items | selectattr('value', 'ne', []) | list | length > 0

- name: Fail the playbook if there were errors (check mode only)
  ansible.builtin.fail:
    msg: The execution has failed because of errors (probably due to missing dependencies caused by check mode).
  when: ansible_check_mode and error_flag is defined and error_flag
...
